Match.WebUI1/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Match.Repository.Abstract;
using Match.Domain.Entities;
using Match.Repository.EF;


namespace Match.WebUI.Controllers
{
    public class ProfileController : Controller
    {
        private readonly IRepositoryCRUD<Profile, int> repository;

        public ProfileController(IRepositoryCRUD<Profile, int> repository)
            
        {
            this.repository = repository;
        }


       public FileContentResult GetImage(int id)
        {

            Profile f = repository.FindBy(id); 
            if (f == null || f.ImageData == null) return null;
            return File(f.ImageData, f.ImageMimeType);

        }

       public FileContentResult GetProfileImage(int imageId)
       {

           ProfileImage f = repository.FindProfileImageBy( imageId);
           if (f == null || f.ImageData == null) return null;
           return File(f.ImageData, f.ImageMimeType);

       }

        

        public ActionResult Index()
        {
            Profile p = new Profile();
           // p.Age = new Age { Id = 1 };


            ResponseModel responseModel = repository.FindAllFor(0);
            responseModel.Profile.DateBirth = DateTime.Today;
            responseModel.Profile.Id = 0;

            return View(responseModel);
        }



        public ActionResult Index1(int id = 5)
        {
            ResponseModel  r = new ResponseModel();
            r.Profile = new Profile();
            r.Profile.Id = id;
            return View(r);
            
        }


        public ActionResult ProfileInfo(int id)
        {
            Profile p = new Profile();
            ResponseModel responseModel = repository.FindAllFor(id);
            return View("ProfileInfo", responseModel);
        }

        //----------------------------------
        public ActionResult Edit(int id=1)
        {
            Profile p = new Profile();
            ResponseModel responseModel = repository.FindAllFor(id);
            return View("Edit", responseModel);
        }

        //-----------------------------------------
        public ActionResult SearchForm(int id = 1)
        {
            Profile p = new Profile();
            ResponseModel responseModel = repository.FindAllFor(id);
            return View("SearchForm", responseModel);
        }

        //---------------------------------
        public ActionResult Search(int id = 1)
        {
           
            ProfileAndSearchView p = ((ProfileRepository)repository).GetProfileAndSearchInfoBy(id);
            return View("Search", p);
        }

        //---------------------------------
        public ActionResult Save(Profile Profile, int id)
        {

            Profile.Id = id;
            repository.Save(Profile);
            return View("Index1", Profile );
        }


        //------------------------------------------------
        public ActionResult List(Profile Profile, int id)
        {
            Profile.Id = id;
            IEnumerable<Profile> pp = ((ProfileRepository)repository).FindByQuery(Profile);

            return View("List", pp);
        }
        //----------------------------------------------------

        

       
        public ActionResult Details(int idForDisplay, int idForMenu)
        {

            ProfileForDisplay pp = new ProfileForDisplay();// repository.FindBy(idForMenu, idForDisplay);


            pp.Profile = repository.FindBy(idForDisplay, true);
    

            return View("Details", pp);
        }



       //---------------------------------------------------------


        public ActionResult SearchSearch(int id = 1, bool useNumerology = false, bool useZodiac = false)
        {
            ResponseModel responseModel = repository.FindByQuery(id, useNumerology, useZodiac);

           return View("List", responseModel);           
        
        }     

//@using (Ajax.BeginForm("AjaxSearch", "Profile", new AjaxOptions(){ OnSuccess= "OnSuccess"}))

        //--------------------------------------------------------------------------------------
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        [HttpPost]
        public JsonResult AjaxSearch(int id, bool useNumerology = false, bool useZodiac = false)
        {
           
            ResponseModel responseModel = repository.FindByQuery(id,  useNumerology, useZodiac);

            return Json(new
            {
                total1 = "0",
                total2 = responseModel.AllProfilesByNumerology.ToString(),
                total3 = "0",
                totals = responseModel.AllProfiles.ToString()
            },
                JsonRequestBehavior.AllowGet);
        }


        //-----------------------------------------------------
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        [HttpPost]
        public JsonResult AjaxSearchResultView(int id, bool useNumerology = false, bool useZodiac = false)
        {

            ResponseModel responseModel = repository.FindByQuery(id, useNumerology, useZodiac);

            // ImageId = p.ProfileImages.Where( s => s.ImageOrderId == 1).FirstOrDefault().Id
            var result = responseModel.Profiles.Select( p => new {
                             //ImageId = p.ProfileImages.Where( s => s.ImageOrderId == 1).FirstOrDefault().Id,
                             DateBirth = p.DateBirth.ToString("MMMM dd, yyyy"),
                             ImageId = p.ProfileImages.OrderBy(s => s.ImageOrderId).Select(s => s.Id),
                             FirstName = p.FirstName,
                             GenderId = p.GenderId,
                             Zodiac = p.Zodiac, Id = p.Id});

            return Json( result, JsonRequestBehavior.AllowGet);
        }     

        
        
        //--------------------------------------------------------------------------------
        public JsonResult SearchTotals(ResponseModel responseModel)
        {
            return Json(new { 
                total1 = responseModel.AllProfilesByNumerology.ToString(),
                total2 = responseModel.AllProfiles.ToString() ,
                 total3 = responseModel.AllProfiles.ToString(),
                     totals = responseModel.AllProfiles.ToString() },
                JsonRequestBehavior.AllowGet);
        }

        //-------------------------------------------------------------------------



             public ActionResult SearchForPage(Profile Profile,  int Submit, 
                 int pageNumber=1, int itemsPerPage=4, int id = 0, bool useNumerology=false)
        {

            if (Submit == 3) return View("Index1");
        
            bool useZeroId = true;
            //bool useZeroId = false;

            Profile.Id = id;
            ResponseModel responseModel = repository.FindByQuery(id, useZeroId, useNumerology);

            IEnumerable<ProfileForDisplay> profilesForDisplay = null;
              //  repository.FindAllForPage(responseModel.Profiles, pageNumber, itemsPerPage);

            if (Submit == 2) return View("ProfileInfo", responseModel); // submit 1 to see view list

            else return View("ListWithDetails", profilesForDisplay); //submit 2 to see Counts

        }



        //---------------------------------------------------
        public ActionResult Help(int id = 0)
        {
            ResponseModel responseModel = new ResponseModel();
            responseModel.Profile = new Profile();
            responseModel.Profile.Id = id;

            return View("Help", responseModel); 
        }        
    }
}

Match.WebUI1/Views/Arxiv/Arxiv1.cshtml
@using Match.Domain.Entities;
@using Match.Repository.EF;
@using Match.WebUI.Infrastructure.HTMLHelpers;
@model ResponseModel


 @using (Html.BeginForm("Search", "Profile"))
 {
<div id="search" class="rounded10">
Which Compatibility Method Do You Prefer<br />

<table class= "tableData">
<tr><th>Compatibility</th><th>Choice</th><th>Price</th><th>Found</th></tr>
<tr><td>Zodiacal            </td><td>@Html.CheckBox("Check1")</td><td>10$  </td><td> <span id="total1">0</span></td></tr>
<tr><td>Numerological        </td><td>@Html.CheckBox("useNumerology")</td><td>10$  </td><td><span id="totals1">@Model.AllProfilesByNumerology</span></td></tr>
<tr><td>Sexual              </td><td>@Html.CheckBox("Check3")</td><td>10$  </td><td><span id="total3">0</span></td></tr>
<tr><td>Total match found  </td><td>      </td><td></td><td><span id="totals">@Model.AllProfiles</span></td><td>
</td></tr>
</table>
@Html.Button("View", new { name = "Submit", value = "1" })
</div>
 
 
  <div class="MatchDiv" >  

<div id="profile" class="rounded10">
@Html.Button("X", new { name = "Submit", value = "3" })

@Html.Hidden("Profile.Id", new { Model.Profile.Id })
@Html.Hidden("id", new { Id = Model.Profile.Id })
<div id="profile1" >

<table class="tableSearchInfo" >
 
<tr><th colspan="3"> My Personal Info</th></tr>
<tr><td>
 


    @Html.LabelFor(p => Model.Profile.LastName)
</td><td>
</td><td>
    @Html.TextBoxFor(p => Model.Profile.LastName)
</td></tr><tr><td>


<span class="redStar">*</span>@Html.LabelFor(p => Model.Profile.FirstName)
</td><td>
</td><td>
@Html.TextBoxFor(p => Model.Profile.FirstName)
</td></tr><tr><td>

<span class="redStar">*</span>@Html.LabelFor(p => Model.Profile.DateBirth)
</td><td>
</td><td>
   @Html.TextBoxFor(m => m.Profile.DateBirth, new { @Value = Model.Profile.DateBirth.ToString("d") })    
</td></tr><tr><td>


 <span class="redStar">*</span>@Html.LabelFor(p => Model.Profile.StatusId)
</td><td>
</td><td>
    @Html.DropDownListForIAttributeSource("Profile.StatusId", Model.Profile.StatusId, Model.Statuses, "Select Status")
</td></tr><tr><td>


   <span class="redStar">*</span>@Html.LabelFor(p => Model.Profile.GenderId)
</td><td>
</td><td>
    @Html.MatchEnumDropDownListFor(p => Model.Profile.GenderValue, "Select Gender")
</td></tr><tr><td>


   <span class="redStar">*</span>@Html.LabelFor(p => Model.Profile.LookingForId)
</td><td>
</td><td>
    @Html.MatchEnumDropDownListFor(p => Model.Profile.LookingForValue, "Select Gender")
</td></tr><tr><td>


    @Html.LabelFor(p => Model.Profile.ImageData)
</td><td>
</td><td>
    @Html.TextBox("Img")
</td></tr><tr><td>
    

  <span class="redStar">*</span>@Html.LabelFor(p => Model.Profile.EMail)
</td><td>
</td><td>
    @Html.TextBoxFor(p => Model.Profile.EMail)
</td></tr><tr><td>


   <span class="redStar">*</span>@Html.LabelFor(p => Model.Profile.Phone)
</td><td>
</td><td>
    @Html.TextBoxFor(p => Model.Profile.Phone)
</td></tr>
</table>
</div>

<p style = "clear:both;"></p>


    
<div id="profile2">
<table>
<tr><td class="tdWithoutDecorSides"><br />I Am</td><td class="tdWithoutDecorSides" >Applications</td><td class="tdWithoutDecorSides"><br />Looging For</td></tr>
<tr><td class="tdWithoutDecorTop">  &nbsp;  </td><td class="tdWithoutDecorBottom">     </td><td class="tdWithoutDecorTop">      </td></tr>
    <tr><td>
        @Html.DropDownListForIAttributeSource("Profile.ReligionId", Model.Profile.ReligionId, Model.Religions, "Select Religion")
    </td><td>
        @Html.LabelFor(p => Model.Profile.ReligionId)
    </td><td>
         @Html.DropDownListForIAttributeSource("Profile.SearchReligionId", Model.Profile.SearchReligionId, Model.Religions, "N/A")
    </td></tr><tr><td>


       
        @Html.DropDownListForIAttributeSource("Profile.SpecifyId", Model.Profile.SpecifyId, Model.Specifies, "Select Specify")
    </td><td>
     @Html.LabelFor(p => Model.Profile.SpecifyId)
    </td><td>
        @Html.DropDownListForIAttributeSource("Profile.SearchSpecifyId", Model.Profile.SpecifyId, Model.Specifies, "N/A")
    </td></tr><tr><td>


        
         @Html.DropDownListForIAttributeSource("Profile.DenominationId", Model.Profile.DenominationId, Model.Denominations, "Select Denomination")
    </td><td>
         @Html.LabelFor(p => Model.Profile.DenominationId)
    </td><td>
         @Html.DropDownListForIAttributeSource("Profile.SearchDenominationId", Model.Profile.SearchDenominationId, Model.Denominations, "N/A")
    </td></tr><tr><td>


        
        @Html.DropDownListForIAttributeSource("Profile.CountryId", Model.Profile.CountryId, Model.Countries, "Select Country")
    </td><td>
        @Html.LabelFor(p => Model.Profile.CountryId)
    </td><td>
        @Html.DropDownListForIAttributeSource("Profile.SearchCountryId", Model.Profile.SearchCountryId, Model.Countries, "N/A")
    </td></tr><tr><td>



       
        @Html.DropDownListForIAttributeSource("Profile.StateId", Model.Profile.StateId, Model.States, "Select State")
    </td><td>
         @Html.LabelFor(p => Model.Profile.StateId)
    </td><td>
         @Html.DropDownListForIAttributeSource("ProfileStateId", Model.Profile.SearchStateId, Model.States, "N/A")
    </td></tr><tr><td>


        
        @Html.TextBoxFor(p => Model.Profile.SearchCity)
    </td><td>
         @Html.LabelFor(p => Model.Profile.City)
    </td><td>
        @Html.TextBox("empty")
    </td></tr><tr><td>


        @Html.TextBoxFor(p => Model.Profile.ZipCode)
    </td><td>   
        @Html.LabelFor(p => Model.Profile.ZipCode)
    </td><td>
         @Html.TextBox("empty")
    </td></tr><tr><td>

        
       
            @Html.DropDownListForIAttributeSource("Profile.HeightId", Model.Profile.HeightId, Model.Heights, "Select Height")
    </td><td>
        @Html.LabelFor(p => Model.Profile.HeightId)
    </td><td>
         @Html.DropDownListForIAttributeSource("Profile.SearchHeightId", Model.Profile.SearchHeightId, Model.SearchHeights, "N/A")
    </td></tr><tr><td>


        
        @Html.DropDownListForIAttributeSource("Profile.WeightId", Model.Profile.WeightId, Model.Weights, "Select Weight")
    </td><td>
    @Html.LabelFor(p => Model.Profile.WeightId)
    </td><td>
         @Html.DropDownListForIAttributeSource("Profile.SearchWeightId", Model.Profile.SearchWeightId, Model.SearchWeights, "N/A")
    </td></tr><tr><td>


      
         @Html.DropDownListForIAttributeSource("Profile.AgeId", Model.Profile.AgeId, Model.Ages, "Select Age")
    </td><td>
      @Html.LabelFor(p => Model.Profile.AgeId)
    </td><td>
         @Html.DropDownListForIAttributeSource("Profile.SearchAgeId", Model.Profile.SearchAgeId, Model.SearchAges, "N/A")
    </td></tr><tr><td>

    
    
       
          @Html.MatchEnumDropDownListFor(p => Model.Profile.SmokeValue, "Select Smoke Type")
    </td><td>
     @Html.LabelFor(p => Model.Profile.SmokeId)
    </td><td>
           @Html.MatchEnumDropDownListFor(p => Model.Profile.SearchSmokeValue, "N/A")
    </td></tr><tr><td>

   
        @Html.DropDownListForIAttributeSource("Profile.ChildrenId", Model.Profile.ChildrenId, Model.HasChildren, "Select Children")
    </td><td>
     @Html.LabelFor(p => Model.Profile.ChildrenId)
    </td><td>
          @Html.DropDownListForIAttributeSource("Profile.SearchChildrenId", Model.Profile.SearchChildrenId, Model.HasChildren, "N/A")
    </td></tr><tr><td>

    
         @Html.MatchEnumDropDownListFor(p => Model.Profile.DisabilityValue, "Select Disability")
    </td><td>
    @Html.LabelFor(p => Model.Profile.DisabilityId)
    </td><td>
         @Html.MatchEnumDropDownListFor(p => Model.Profile.SearchDisabilityValue, "N/A")
    </td></tr><tr><td>


       
        @Html.DropDownListForIAttributeSource("Profile.EducationGradeId", Model.Profile.EducationGradeId, Model.EducationGrades, "Select Education")
    </td><td>
     @Html.LabelFor(p => Model.Profile.EducationGradeId)
    </td><td>
          @Html.DropDownListForIAttributeSource("Profile.SearchEducationGradeId", Model.Profile.SearchEducationGradeId, Model.EducationGrades, "N/A")
    </td></tr><tr><td>


        @Html.TextBoxFor(p => Model.Profile.SearchAncestorsFrom)
    </td><td> 
    
         @Html.LabelFor(p => Model.Profile.AncestorsFrom)
    </td><td>
         @Html.TextBox("empty")      
    </td></tr><tr><td>

         
        
         @Html.MatchEnumDropDownListFor(p => Model.Profile.VirginValue, "Select Virginity")
    </td><td>
    @Html.LabelFor(p => Model.Profile.VirginId)
    </td><td>
          @Html.MatchEnumDropDownListFor(p => Model.Profile.SearchVirginValue, "N/A")
    </td></tr>
<tr><td class="tdBottomWithoutDecorBottom">  &nbsp;  </td><td class="tdBottomWithoutDecorTop">     </td><td class="tdBottomWithoutDecorBottom">      </td></tr>
</table>
<br /><br />
<div id="aboutmyself">
<br />
 @Html.LabelFor(p => Model.Profile.AboutMyself)<br /><br />

@Html.TextAreaFor(p => Model.Profile.AboutMyself)

		   

</div>


@Html.Button("Submit", new { name = "Submit", value = "2" }) 
</div>

</div>
</div>
    
     
     
 } 
 
 

 
       
      

Match.WebUI1/Views/Arxiv/Details.cshtml
@{
    ViewBag.Title = "Details";
@using Match.Domain.Entities;
@using Match.Repository.EF;
@using Match.WebUI.Infrastructure.HTMLHelpers;
@model ProfileForDisplay

@{
    Layout = "~/Views/Shared/_MenuLayout.cshtml";
}
@section Scripts{
@Styles.Render("~/Content/Foundation/customcss/mycustom.css")

@Scripts.Render("http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js")
@Scripts.Render("http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js")


}

@section MainContent{

<div class="row">
<div class="large-8 small-centered  large-uncentered columns">

<fieldset class="searchinfoGray ">
<legend>@Model.Profile.FirstName, @Model.Profile.AgeFromDateBirth</legend>
<div class="row">
 <div  class="small-12 columns">

 <div class="row">
  <div  class="medium-4 columns">
 
   <div class="row">
    <div  class="columns">
    

      @if (Model.Profile.ProfileImages == null)
      {   
         <div class="resize-image" style="background: url('../../Content/Images/no-image.jpg')"></div> 
      }
      else
      {

        <div class="resize-image" style="background: url('@Url.Action("GetProfileImage", "Profile", new { imageId = Model.Profile.Id })')"></div>
      }                     
                   
  </div> 
  </div>


  

  
   </div>
   <div  class="medium-8 columns">               
          




<div id="settings_accordion" >

  <h3><a href="#">Personal information</a></h3>
  <div class="wrapper">



<div class="row">
       <div class=" medium-4 columns medium-text-right  small-text-left ">Age</div>
     <div class="medium-6 small-12 columns small-text-left end ">@Model.Profile.AgeFromDateBirth</div>
  </div> 


  
  <div class="row">
     <div class=" medium-4 columns medium-text-right  small-text-left ">Gender</div>
     <div class="medium-6 small-12 columns small-text-left end ">@Model.Profile.GenderValue</div>
  </div> 
  
   

  <div class="row"> 
     <div class=" medium-4 columns medium-text-right  small-text-left ">Marital status</div>
     <div class="medium-6 small-12 columns small-text-left end ">@Model.Profile.Status.Name</div>
  
  </div>  



  <div class="row"> 

  <div class=" medium-4 columns medium-text-right  small-text-left ">Children</div>
     <div class="medium-6 small-12 columns small-text-left end ">@Model.Profile.Children.Name</div>
  </div>  


  <div class="row">
       <div class=" medium-4 columns medium-text-right  small-text-left ">Country</div>
     <div class="medium-6 small-12 columns small-text-left end ">@Model.Profile.City</div>
  </div> 


  <div class="row"> 
    <div class="s medium-4 columns medium-text-right  small-text-left ">Weight</div>
     <div class="medium-6 small-12 columns small-text-left end ">@Model.Profile.Weight.Name</div>
  </div> 

 <div class="row"> 
      
     <div class="medium-4 columns medium-text-right  small-text-left ">Height</div>
  
     <div class="medium-6 small-12 columns small-text-left end ">@Model.Profile.Height.Name</div>

  </div> 


  <div class="row"> 
     <div class=" medium-4 columns medium-text-right  small-text-left ">Race</div>
     <div class="medium-6 small-12 columns small-text-left end " >@Model.Profile.Race.Name</div>
  </div> 


  <div class="row"> 
     <div class=" medium-4 columns medium-text-right  small-text-left ">Smoke</div> 
     <div class="medium-6 small-12 columns small-text-left end " >@Model.Profile.Smoke.Name</div>
  </div> 


  <div class="row"> 
     <div class=" medium-4 columns medium-text-right  small-text-left ">Disability</div>
     <div class="medium-6 small-12 columns small-text-left end " >@Model.Profile.Disability.Name</div>
  </div> 


  <div class="row"> 
     <div class=" medium-4 columns medium-text-right  small-text-left ">Education</div>
     <div class="medium-6 small-12 columns small-text-left end ">@Model.Profile.EducationGrade.Name</div>
  </div> 
  

  <div class="row"> 
     <div class=" medium-4 columns medium-text-right  small-text-left ">Occupation</div>
     <div class="medium-6 small-12 columns small-text-left end ">@Model.Profile.Occupation.Name</div>
  </div> 


  <div class="row"> 
     <div class=" medium-4 columns medium-text-right  small-text-left ">Income</div> 
     <div class="medium-6 small-12 columns small-text-left end ">@Model.Profile.Income.Name</div>
  </div> 



   <div class="row">
     <div class=" medium-4 columns medium-text-right  small-text-left ">Religion</div>
     <div class="medium-6 small-12 columns small-text-left end ">@Model.Profile.Religion.Name</div>
  </div>
  </div>
  
  
  
  <h3>Numerology</h3>
  <div class="wrapper">
<div class="row">
       <div class=" small-12 columns   small-text-left ">Life Path Number @Model.Profile.LifePathNumber</div>
        <div class="small-12 columns   small-text-left ">Long text</div>
       <div class="small-12 columns   small-text-left ">********* *** **** ******* ******** ****** ****** ****** ******</div>
  </div >

  </div>
  

<h3>Zodiac</h3>
  <div class="wrapper">
<div class="row">
       <div class=" small-12 columns   small-text-left ">Zodiac Sign @Model.Profile.Zodiac</div>
        <div class="small-12 columns   small-text-left ">Long text</div>
       <div class="small-12 columns   small-text-left ">****** ****** ****** ****** ********* ****** ****** ******* ****** ******* ***</div>
  </div>

 </div>
  




  

  <h3>Contact</h3>
  <div class="wrapper">



<div class="row">
       <div class=" medium-4 columns medium-text-right  small-text-left ">E-mail</div>
     <div class="medium-6 small-12 columns small-text-left end ">@Model.Profile.EMail</div>
  </div> 
<div class="row">
       <div class=" medium-4 columns medium-text-right  small-text-left ">Phone</div>
     <div class="medium-6 small-12 columns small-text-left end ">@Model.Profile.Phone</div>
  </div>
  
  </div>
  
   
  </div> 



   </div>                                           
                   
 </div>            
               


 </div>
 </div>
            
  </fieldset>  

</div>

</div>

  
<script  type="text/javascript">
    $(document).ready(function () {
        /* Converts the h3s and divs into an accordion.
        active: false collapses all the panels initially.
        collapsible: true is necessary for active: false to work.
        heightStyle: "content" makes each panel as tall as its contents.
        */
        $('#settings_accordion').accordion(
    {
        collapsible: true,
        active: false,
        heightStyle: "content"
    }

  );


        //$(".ad_container:gt(3)").hide();



        /* Attaches a handler function to the notifications checkbox that toggles the visibility of the notification sub-options. */
        $('input#cb_enable_notify').change(function () {
            $('div.sub_options').toggle();
        });

    });
</script>
  }

 

Match.WebUI1/Views/Arxiv/List1.cshtml
@using Match.Repository.EF;
@using Match.WebUI.Infrastructure.HTMLHelpers;
@using Match.Domain.Entities;
@model ResponseModel

@{
    Layout = "~/Views/Shared/_MenuLayout.cshtml";
}



@section MainContent{
  
 <div  id="divDetailsInfo" >           
        <ul class="items-list">
           @if (Model != null)
           {
               foreach (Profile p in Model.Profiles)
               {
                   if (p != null)
                   {
                   <li class="item-detail">
                    <a class="item-productimage-link" 
                             href="@Url.Action("Details", "Profile",
                               new { idForDisplay = p.Id, idForMenu = Model.Profile.Id }, null) ">




                       @if ( p.ProfileImages == null){ 
                              <img   src="../../Content/Images/no-image.jpg" class="item-productimage" width="200" height="200" alt="no-image" />  
                       }
                       else {
     
                         
                             foreach( ProfileImage pp in p.ProfileImages)
                             {         
                                if (pp.ImageOrderId == 1) {
	                               <img src="@Url.Action("GetProfileImage", "Profile", new { imageId = pp.Id })" width="200" height="200"  
                                            class= "first" alt = "image"/>
                                 }
                               else {
                               <img src="@Url.Action("GetProfileImage", "Profile", new { imageId = pp.Id })" width="200" height="200"  
                                    alt = ""/>
                               }
                            }
                                         
                           }                  
                                                                                 
                                                                                                
                    </a>
                    
                    <div class="item-price">
                          <a class="item-productimage-link" 
                             href="@Url.Action("Details", "Profile",
                               new { idForDisplay = p.Id, idForMenu = Model.Profile.Id }, null) ">@p.FirstName  @p.LastName</a>
                               <br />
                    </div>
               </li>}
          }}
 </ul>
</div>
 }